### ISSUE TITLE
Bring word gender as a separate key  

### ISSUE THREAD

**Issue by ytrofimov** [imankulov/linguee-api#1]
Hi Roman, thanks a lot for the API! 
Feature request that would make this API much better than google translate API for learning new words: could you bring out the gender of the word as a separate key? 
i.e. https://linguee-api.herokuapp.com/api?q=sonne&src=de&dst=en
format this 
> "text": "Sonne",
> "word_type": "noun,Â feminine",

into this

> "text": "Sonne",
> "word_type": "noun",
> "gender": "feminine" 

as a bonus if you could add actual article (feminine = die, masculine = der, neuter = das), that would be total ace!

> "article": "die"

**Comment by imankulov** [comment]
Hi! Thanks for the feedback. Now the parser returns a structured information about the part of speech, gender (whenever if makes sense) and a plural form flag (if it's true).

> as a bonus if you could add actual article (feminine = die, masculine = der, neuter = das), that would be total ace!

With that information it shouldn't be a problem for your case, yet obviously it's quite non-trivial to generalize. For example, English articles don't depend on gender, but change "a" to "an" or alternatively you can use "the". Also, in some cases you shouldn't use any articles at all. Different languages have different grammar rules and it goes way out of the scope of a simple parser.

**Comment by ytrofimov** [comment]
@imankulov wow, didn't expect such fast response, thanks a lot!
