### ISSUE TITLE
Bug - Internal Server Error - Multiple "Grammar Infos"

### ISSUE THREAD

**Issue by irico1997** [imankulov/linguee-api#12]
Hi! Love this project, it has helped me a lot in my studies. I've found one bug, some words have multiple possible entries under ```span.tag_lemma > span.tag_lemma_context > span.placeholder > span.grammar_info``` but the current model only matches 0-1 time. An example word is "wünschen" (de -> en). It gives "internal error 500" on the API test page, I added a test for this word and this is the error message.
```
self = <xextract.parsers.String object at 0x1093db940>
nodes = [<HtmlXPathExtractor data='<span class="grammar_info">Akk</span>'>, <HtmlXPathExtractor data='<span class="grammar_info">Akk</span>'>]
context = {'url': None}

    def _process_nodes(self, nodes, context):
        # validate number of nodes
        num_nodes = len(nodes)
        if not self.quantity.check_quantity(num_nodes):
            if self.name:
                name_msg = '(name="%s")' % self.name
            else:
                name_msg = '(xpath="%s")' % self.raw_xpath
>           raise ParsingError(
                'Parser %s%s matched %s elements ("%s" expected).' %
                (self.__class__.__name__, name_msg, num_nodes, self.quantity.raw_quantity))
E           xextract.parsers.ParsingError: Parser String(name="grammar_info") matched 2 elements ("?" expected).
```
I've been making small modifications to add a field on my fork and found this. Not sure how to cleanly fix/didn't want to overstep, but if I do fix it I'll share how

**Comment by imankulov** [comment]
Great catch. Thanks a lot for reporting it. I think I fixed it in https://github.com/imankulov/linguee-api/commit/32e5846ecdde93f5400ac2124fa1b8702a620c88
