### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by tomsturges** [imankulov/linguee-api#18]
Hello,

Would you kindly be able to give me a few pointers on how to install this? I've had a look at the documentaiton and the "[playground](https://linguee-api-v2.herokuapp.com/docs)" but it's no clearer to me how to get started. My programming skills are weak, but I think with a few pointers this tool could be useful for me learning German.

**Comment by imankulov** [comment]
Hey @tomsturges! Thanks for considering this project.

Linguee-API turns the human-readable output of Linguee into [HTTP API](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction), a machine-readable interface. This provides a foundation for creating other services. If, as you admit, your programming skills are weak, maybe the tool is not the best choice.

**Comment by tomsturges** [comment]
Hi thanks for getting back to me. Perhaps you're right. I'm tempted to try though [more details below]. I guess I need to "make" the code with the Makefile. Is it possible to provide installation instructions, or is it actually rather complicated even to install it?

[more details] What I want to accomplish is this. As an input use a .csv file of german vocabulary. Then I would have some code that would extract all the sample phrases (and translations) for each vocabulary word and create another .csv file with these. I thought I could use a bash/python script, that interacts with your code, plus some kind of Regex. My coding skills are certainly not strong, but I do have some experience with basic coding for my work as a scientific reseracher but I'm certainly

**Comment by imankulov** [comment]
@tomsturges, thanks for outlining your goals. Also, a good point is that the API doesn't provide any usage examples.

I extended the README with some examples.

- [Usage examples with Python and requests](https://github.com/imankulov/linguee-api/#usage-examples-with-python-and-requests)
- [Usage examples with Bash, curl, and jq](https://github.com/imankulov/linguee-api/#bash-curl-and-jq-usage-example)

Please let me know if this helps.

**Comment by imankulov** [comment]
Also, you may consider using a [translatepy](https://github.com/Animenosekai/translate) project. It provides the Python and Bash interface and doesn't require installing an API server.
