### ISSUE TITLE
503 Error

### ISSUE THREAD

**Issue by jzw2** [imankulov/linguee-api#19]
Certain queries return a 503 error, I don't know what the exact cause is, but it could be related #11, as the entries there all return 503.

**Comment by imankulov** [comment]
Hey @jzw2! Thanks for reporting. Do you have any examples of failing queries?

**Comment by jzw2** [comment]
This is strange, but last night all three queries in #11 failed with a 503, but today it seemed to be working just fine. So there may be some random factor, since also I've noticed that some queries that worked yesterday don't work today.


Example: https://linguee-api-v2.herokuapp.com/api/v2/translations?query=stolz%20sein%20auf&src=de&dst=en&guess_direction=false

returns

```
{"message":"The Linguee server returned 503"}
```
This is the list of all queries that return with the error, as of today, 

```
eifersüchtig auf
neidisch sein auf
stolz sein auf
sich bedanken bei
bleiben bei
sich entschuldigen bei
sich entscheiden für
sich entschuldigen für
sich interessieren für
sein für
sorgen für
geeignet sein für
gut sein für
schlecht sein für
nützlich sein für
wichtig sein für
zuständig sein für
stimmen für
protestieren gegen
stimmen gegen
allergisch sein gegen
sein gegen
sich entscheiden gegen
sich verlieben in
verliebt sein in
angfangen mit
beginnen mit
aufhören mit
sich beschäftigen mit
reden mit
sprechen mit
streiten mit
sich unterhalten mit
vergleichen mit
sich verstehen mit
befreundet sein mit
einverstanden sein mit
fertig sein mit
zufrieden sein mit
fragen nach
sich erkundigen nach
schmecken nach
sich sehnen nach
sich ärgern über
sich aufregen über
berichten über
sich beschweren über
diskutieren über
streiten über
sich freuen über
sich informieren über
lachen über
nachdenken über
froh sein über
glücklich sein über
traurig sein über
sich bemühen um
bitten um
es geht um
es handelt sich um
sich kümmern um
etwas bewerben 
sich bewerben um
sich fürchten vor
```

**Comment by jmelkor** [comment]
The same issue happens with this link [https://linguee-api-v2.herokuapp.com/api/v2/translations?query=hit&src=en&dst=ru](https://linguee-api-v2.herokuapp.com/api/v2/translations?query=hit&src=en&dst=ru).

It returns
```
{"message":"The Linguee server returned 503"}
```

**Comment by imankulov** [comment]
Thanks for providing more details, folks!

I'm afraid there's not much I can do here. As you know, Linguee API depends on the availability of the upstream website (i.e., https://linguee.com). If the upstream website is not available, then the API proxy can't do much about it. It looks like around the time you made the requests, the Linguee website was down or partially unavailable, returning 503 error responses to some or all the requests.

Now everything seems to be back to normal. I'm closing down the issue. If you have more questions or comments, please leave them to the closed issue. Thanks!
