### ISSUE TITLE
Deploy to Heroku error

### ISSUE THREAD

**Issue by tisfeng** [imankulov/linguee-api#21]
Hi, I am new to Heroku, I am using it for the first time and I am getting this error, I didn't make any changes, just clicked the deploy button, is there something I am missing?

```
-----> ^3.8 is not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)
 !     Push rejected, failed to compile Python Poetry app.
 !     Push failed
```

<img width="818" alt="image" src="https://user-images.githubusercontent.com/25194972/180927256-a2a162b9-aeab-431d-9785-85996eeded7c.png">

**Comment by imankulov** [comment]
Thanks for the report, @tisfeng. It should be fixed in the latest version. Please, try to install it with a "Deploy to Heroku" button again, and feel free to re-open the ticket if it doesn't work still.
