### ISSUE TITLE
Hope to add 'often used' property

### ISSUE THREAD

**Issue by tisfeng** [imankulov/linguee-api#22]
Hi, thank you for the linguee api, I like it very much, but I find it is missing 'often used' property, could you please add them? Thank you very much!

## [good](https://www.linguee.com/english-chinese/search?source=auto&query=good)

<img width="941" alt="image" src="https://user-images.githubusercontent.com/25194972/180928919-c701c805-0ca0-42a6-af2f-d58540f1e248.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/25194972/180928780-dfb43d5a-953a-4364-a36e-568272e30ed6.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/25194972/180928368-32fc00b3-91de-4b96-9531-c98400ca079c.png">

**Comment by imankulov** [comment]
Hey, @tisfeng! Thanks for the suggestion. I'll address it later today. Likely, over the weekend.

**Comment by imankulov** [comment]
Hey @tisfeng. I added a new attribute, `usage_frequency`. The attribute can take values `often`, `almost_always` or None.

Request sample: https://linguee-api-v2.herokuapp.com/api/v2/translations?query=good&src=en&dst=zh&guess_direction=false

![Screenshot](https://user-images.githubusercontent.com/75075/182197096-caa1c4bb-9fb4-4ca1-82d9-b25176d93315.png)


[Version 2.4.0 is available on PyPI](https://pypi.org/project/linguee-api/2.4.0/)

**Comment by tisfeng** [comment]
@imankulov  Okay, thanks so much!
