### ISSUE TITLE
What does 'featured' mean in response?

### ISSUE THREAD

**Issue by Beau-xu** [imankulov/linguee-api#24]
Hi, thanks a lot for your work.

But I am wondering what the True/False of 'featured' means in response.

For example, the 'featured' appearing in lemma and translations:
```
[{'featured': True,
  'text': 'empfangen',
  'pos': 'verb',
  'grammar_info': None,
  'audio_links': [{'url': 'https://www.linguee.com/mp3/DE/61/61b5820b33b275797b427b115ff6cc38-201.mp3',
    'lang': 'German'}],
  'translations': [{'featured': True,
    'text': 'receive',
    'pos': 'verb',
    'audio_links': [{'url': 'https://www.linguee.com/mp3/EN_US/cb/cbd71f0d3114139d38a8d080d610e5fd-200.mp3',
      'lang': 'American English'},
......
```

**Comment by imankulov** [comment]
## Featured lemmas

Linguee doesn't distinguish in the interface featured lemmas. Frankly, I don't know how it decides which lemmas should be marked as featured and which ones are not.

For example, in the English-Portuguese translation of [feature](https://www.linguee.com/english-portuguese/search?query=feature), the first two lemmas are marked as featured, and the third one does not.

In the English-Chinese translation of [assist](https://www.linguee.com/english-chinese/search?source=auto&query=assist), all three lemmas are marked as featured.

🤷 

## Featured translations

It's easier. All non-featured translations appear under the "less common:" remark in the Linguee interface.

![Screenshot 2022-08-05 at 10 37 11](https://user-images.githubusercontent.com/75075/183050107-6666b614-177d-447d-8718-820d8637c0cb.png)
