### ISSUE TITLE
Missing time variants of verbs

### ISSUE THREAD

**Issue by NetramSamoht** [imankulov/linguee-api#26]
A very good API :)
The only missing feature are the additional information about the tense. 
I have unfortunately no Python experience to implement this...

Is there a good reason why you can't grab this data?
If not, you may eventually have time and want to implement it.

Thanks for your work ;)

**Comment by imankulov** [comment]
Hey @novaCTM. Sorry, I missed your question.

If it's still relevant, can you please provide an example of what you mean by "time form"? Is it something that's available in English?

![Screenshot 2022-10-09 at 22 40 10](https://user-images.githubusercontent.com/75075/194780721-c651daba-dc92-438f-b488-41b9e3faff54.png)

**Comment by novaCTM** [comment]
YES, that's exactly what I meant.
Sorry for unclear discription.
I am working on a vocabulary trainer where the avilability of the tense would be a nice feature!

**Comment by imankulov** [comment]
Hey @NetramSamoht! I finally implemented the change you asked for and updated the sample installation at https://linguee-api.fly.dev.

If it's still relevant, you can test it at https://linguee-api.fly.dev/api/v2/translations?query=shrink&src=en&dst=pt&guess_direction=false&follow_corrections=always.

The API returns an array of forms for each lemma if it finds them on the page.

<img width="964" alt="Example" src="https://user-images.githubusercontent.com/75075/202850700-3186e65f-9efe-4ff5-be79-1967e9996296.png">

**Comment by NetramSamoht** [comment]
Thank you so much!!! I'm very happy now 👍
