### ISSUE TITLE
Some words just don't translate

### ISSUE THREAD

**Issue by arkady-mirzabekyan** [imankulov/linguee-api#29]
Some examples:
```
https://linguee-api.fly.dev/api/v2/translations?query=bein&src=de&dst=en&guess_direction=False
https://linguee-api.fly.dev/api/v2/translations?query=Bahnhof&src=de&dst=en&guess_direction=False
https://linguee-api.fly.dev/api/v2/translations?query=beginnen&src=de&dst=en&guess_direction=False
https://linguee-api.fly.dev/api/v2/translations?query=aussehen&src=de&dst=en&guess_direction=False
https://linguee-api.fly.dev/api/v2/translations?query=Autobahn&src=de&dst=en&guess_direction=False
```

All returns 
```
{
	"message": "The Linguee server returned 503"
}
```

But there is a translation for them 
https://www.linguee.com/english-german/search?source=auto&query=Autobahn

Didn't find a patter. Am I doing something wrong?

**Comment by imankulov** [comment]
Hey @arkady-mirzabekyan, 

This error means that the Linguee website temporarily blocks the API client for sending too many requests. If you use the sample API server on https://linguee-api.fly.dev/, you can try to send the request later or consider installing your API server, where you won't share the same IP address with other users.

The error is so common that I've just added an explanation to the [FAQ](https://github.com/imankulov/linguee-api#the-api-server-returns-the-linguee-server-returned-503) and to the error message itself.

Hope this helps.
