### ISSUE TITLE
How to get the sample sentences for a phrase?

### ISSUE THREAD

**Issue by deemeetree** [imankulov/linguee-api#5]
Hello, thank you for this software, what a great idea!

I wanted to ask you: is there a way to make a query where I would simply get a list of all the sentences where a phrase is used in the native language? You know how Linguee shows it automatically when you search? So, not the translations, but, rather the contextual sentences?

Thanks!

**Comment by imankulov** [comment]
Hey @deemeetree. If it's still relevant, I rewrote the project from scratch, and both Linguee-curated examples and external sources are available in the API as independent API endpoints.

Here's the documentation: https://linguee-api-v2.herokuapp.com/docs
