### ISSUE TITLE
`inexact_matches` always returns null

### ISSUE THREAD

**Issue by mariaheine** [imankulov/linguee-api#6]
## Behaviour
Searching for string `katz` in german to english returns an empty `exact_matches` array and a null `inexact_matches`

![image](https://user-images.githubusercontent.com/24575912/111026895-36836280-83ed-11eb-8dc8-eee52af27d22.png)

## Expected
Searching for an incomlete word returns an array of word suggestions as when directly using linguee webapp.

![image](https://user-images.githubusercontent.com/24575912/111026921-59ae1200-83ed-11eb-9068-2713bf0f0892.png)

## Explanation
Oh hai so much thanks for your repo, this thing is so cool 🍰 Sorry if I misunderstood the `inexact_matches` field but it is always null and I assumed it was used for something but you didn't say anything about it in your README

**Comment by imankulov** [comment]
Thanks for the report! I will try to find time to address the issue by the end of the week.

**Comment by imankulov** [comment]
Hey @mariaheine, I have a question that may sound a bit odd. Do you care about the implementation details of linguee-api, or as long as the API solves the issue, you don't care about the rest?

I am asking because the current implementation is written in golang. The project was abandoned long ago, and I haven't worked with golang since then. For me, it would be easier and faster to re-implement the API with Python than to add extra features to its golang version. Would the Python version work for you?

**Comment by mariaheine** [comment]
Personally, for me Python would be even better!

**Comment by imankulov** [comment]
Awesome. Python it is. I'll keep you posted.

**Comment by imankulov** [comment]
Hey @mariaheine, let me provide some status update on the subject.

Unfortunately, I got swamped with other tasks and postponed this work. I don’t plan to abandon it, though. Hopefully, I’ll release the new version by the end of the week.

Also, I must notice that “inexact matches” is not quite what you thought it was. I should make it more clear from the beginning, but I missed the mismatch myself.

What’s somewhat misleadingly called “inexact matches” in the API has the name “Examples” in the user interface of Linguee. The parser has a bug indeed, as it doesn’t return anything, but the output should be different. As for your example, the current version of Linguee API doesn’t parse the output of suggestions.

Thanks for understanding!

<img width="886" alt="Inxeact Matches" src="https://user-images.githubusercontent.com/75075/114350184-c6d5d400-9b60-11eb-9d95-470f9505259c.png">

**Comment by mariaheine** [comment]
Oki, thats great to hear! Also thank you for the clarification, I kind of expected the output of suggestions to be more problematic to parse aswell.

**Comment by imankulov** [comment]
Good news! Finally, I rewrote the code in Python and released the second version of the API.

On top of this, I implemented the /autocompletions API endpoint that parses the output of the Linguee autocompletion.

The API documentation and playground are available here https://linguee-api-v2.herokuapp.com/docs.

The output for the word "katz" will look like this: https://linguee-api-v2.herokuapp.com/api/v2/autocompletions?query=katz&src=de&dst=en.

<img width="1452" alt="autocompletions example" src="https://user-images.githubusercontent.com/75075/115994672-e690e180-a5cf-11eb-99c8-604e27f439a5.png">


I think your question is finally addressed, and I'm closing down the issue. If you have any questions or concerns, please re-open it or create a new one.
