### ISSUE TITLE
get AKK indicator for German verbs

### ISSUE THREAD

**Issue by mutasie** [imankulov/linguee-api#7]
Hello,
When I do a German -> English dictionary lookup, for German verbs, I see that there are indications like "etw.Akk ~" that shows up on the front end. However, when I look for it on the JSON output, I do not see that. Is this something that can be pulled in to JSON? 

Here is an example to reproduce the issue. look up the word "bringen" in German. I am adding an image below.

![image](https://user-images.githubusercontent.com/828611/115738434-582d1d80-a38d-11eb-88f2-e98081c07e9b.png)

Thank you for looking into this.

Allen

**Comment by imankulov** [comment]
Hey @mutasie!

Around the time you created the issue, I happened to rewrite the API from scratch using Python. I changed the API structure and the format of the API responses.

On top of these changes, I created a PR #7 that adds the optional field "grammar_info" to API responses. That's how it looks.

<img width="1061" alt="API output" src="https://user-images.githubusercontent.com/75075/115986914-8d628700-a5aa-11eb-9a1f-632618ddc175.png">


The playground for the code in the PR is available at https://linguee-api-pr7.herokuapp.com/docs.

Can you please take a look and tell me if it's something that you had in mind. I know close to nothing about German grammar, so your input is very valuable.

**Comment by mutasie** [comment]
Hi Roman,
Thank you so much for working on this. I really appreciate it! The
"grammar_info is super helpful and yes, this looks very good. And thanks
for brining in the link to the audio files as well. Very helpful.

I did notice something missing from the screenshot: the example sentence in
the "translations" section is no longer in the JSON output. From the
screenshot that I sent before, there is a sentence that says "Die Wolken
werden Regen bringen." Could you bring this back to the JSON?

Thank you so much for working on this. Version 2 looks excellent. Let me
know if there is anything else I can help you test.

Allen

**Comment by imankulov** [comment]
@mutasie, thanks a lot for the feedback and the report.

As for the translation examples, indeed, it's something that I overlooked. I created a separate issue to keep track of it: https://github.com/imankulov/linguee-api/issues/10.

As for this issue, I will close it down as soon as I merge the PR.

If you have more questions or feedback, don't hesitate to create new issues to discuss.

**Comment by imankulov** [comment]
The PR #8 got merged and deployed.
